# Generated by Django 3.2.25 on 2024-07-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(default='srsofts', max_length=200),
        ),
    ]
