# Generated by Django 3.2.25 on 2024-07-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_book_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
